### ISSUE TITLE
Taskwarrior integration node

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/praefectus#11]
There should be a fully-fledged integration with Taskwarrior:
- we should be able to read all the changes from Taskwarrior instance
- we should be able to export changes from Praefectus back to the Taskwarrior
- merge changes on import/export properly
- search for data conflicts of any kind, and report them to the user

Depends on:
- [ ] #10 (since we need configuration to seek for Taskwarrior instance and to know whether the integration is enabled at all)
- [ ] #9 (since we need to store data a lot)
- [ ] #6 (since we need to know what to store)
- [ ] #8 (since Taskwarrior integration _is_ a separate node by design)
- [ ] #7 (since we need to know what/how to merge)
