### ISSUE TITLE
Simple UI/UX to navigate the database

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/praefectus#13]
While the UX ideas aren't finalized yet, we'll need a simple UI already on this work stage.

So, I propose to introduce some basic command line parsing and command set similar to the one of Taskwarrior, which will work with our database and will help to perform some basic task maintenance set.

It'll need to be properly documented, but I impose no requirements to finalize it right now.

Depends on:
- [ ] #5 (we'll need a basic app to work with)
- [ ] #9 (we'll need a database to operate on)
- [ ] #6 
- [ ] #7 
- [ ] #8 (we'll need all the basic design tasks to be solved before we can start adding any terminal UI)

**Comment by ForNeVeR** [comment]
Initial RFC about the command line interface will be published as part of #16.
